server:
  port: 9003

spring:
  application:
    name: DOCTOR-SERVICE
  datasource:
    url: jdbc:h2:mem:doctor
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
